[package]
name = "yt-pod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.17"
chrono = { version = "0.4.22", features = ["serde"] }
color-eyre = "0.6.2"
futures = "0.3.25"
html-escape = "0.2.11"
quick-xml = "0.22.0"
rss = { version = "2.0.1", features = ["serde", "url", "mime", "validation"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_derive = "1.0.145"
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["fs"] }
uuid = { version = "1.2.1", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
youtube_dl = { version = "0.7.0", default_features = false, features = ["yt-dlp", "tokio"] }
ytd-rs = { version = "0.1.7", features = ["yt-dlp"] }
