name: CD

on: 
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "vpod:dev"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config fly.staging.toml --local-only


